name: gctg
channels:
  - defaults
dependencies:
  - anyio=3.5.0
  - blas=1.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - click=8.1.7
  - distro=1.8.0
  - h11=0.12.0
  - h2=4.0.0
  - hpack=4.0.0
  - httpcore=0.15.0
  - httpx=0.23.0
  - hyperframe=6.0.1
  - intel-openmp=2023.1.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openai=1.3.6
  - openssl=3.0.12
  - pandas=2.1.4
  - pandas-stubs=2.1.4.231227
  - pip=23.3.1
  - pydantic=1.10.12
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-dotenv=0.21.0
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - readline=8.2
  - rfc3986=1.4.0
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tqdm=4.65.0
  - types-pytz=2022.4.0.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
      - charset-normalizer==3.3.2
      - et-xmlfile==1.1.0
      - idna==3.6
      - openpyxl==3.1.2
      - requests==2.31.0
      - tzdata==2023.4
      - urllib3==2.1.0
